### ISSUE TITLE
Where can I learn about how this works?

### ISSUE THREAD

**Issue by andrewrk** [gonzoua/rpi3-psci-monitor#3]
I'm working on a bare metal application for the rpi3 and I've gotten as far as spinning 3 of the cores and having the 4th core writing "hello world" to the UART.

The next thing I'm trying to do is disable the 3 cores that I'm not using (for now) so that they don't waste power / generate excess heat when I only need one core. If I understand correctly I need to use the PSCI interface to the system in order to do that.

I've been reading technical reference manuals and perusing the linux and freebsd source code, and I'm gradually learning this stuff, but it's really slow going. Do you have any recommended materials for me to look at that can give me a jump start? Is there something I could read that would help me to understand every line of this repository and what it does?

Cheers, and thanks for the helpful example.

**Comment by gonzoua** [comment]
I wrote up a bit about Pi3 and FreeBSD/PSCI in my blog:

https://kernelnomicon.org/?p=714
https://kernelnomicon.org/?p=718
The PSCI spec can be found here: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0022c/index.html

I don't think you need PSCI implementation for it though. You might be OK with using "wfe" instruction in your spin loop.

PSCI is a standardized way to manage power options, so instead of implementing multiple platform-specific functions in an OS or bare metal app, you can implement one driver that uses the PSCI interface. This particular repo implements SMP-related spin-up function and can't be used for anything else. So if you're writing from scratch and don't care about portability you're probably better off implementing it in your app. I am not an expert and you'll have to look up more information but as I see it there are two options:

- In your app code use spin loops with "WFE" (Wait For Event) instruction inside that puts CPU in idle mode 
- Check if there is a way to manage CPU state through VideoCore firmware. ARM Trusted Firmware now has RPi3 support so you might want to check its code for any references on how to manage power. I don't know if there are any though. The source code: https://github.com/ARM-software/arm-trusted-firmware/tree/master/plat/rpi3

**Comment by andrewrk** [comment]
Thank you for your time! This is incredibly helpful.
